import type { BulletinItem } from "@/lib/bulletin";

export const BOWER_SEED_ITEMS: BulletinItem[] = [
  {
    id: "seed-funding-1",
    title: "Global Aurexis Summit 2026",
    description:
      "Let us innovate, build, and shape the digital civilization together. Connect, collaborate, and create the future.",
    category: "funding",
    status: "published",
    dateLabel: "Deadline: 10-11 April, 2026",
    amountLabel: "Up to Rs. 100,000 lakh",
    itemOrder: 1,
    source: "seed",
  },
  {
    id: "seed-funding-2",
    title: "Innovate for Impact Challenge 2026",
    description:
      "Open to early-stage, for-profit startups in the AgTech space.",
    category: "funding",
    status: "published",
    dateLabel: "Deadline: 15 April, 2026",
    amountLabel: "Up to Rs. 45,00,000",
    itemOrder: 2,
    source: "seed",
  },
  {
    id: "seed-funding-3",
    title: "Startup India Seed Fund Scheme",
    description:
      "For startups in DeepTech, AI/ML, Cybersecurity, IoT, Blockchain, Fintech, EdTech, and HealthTech.",
    category: "funding",
    status: "published",
    dateLabel: "Deadline: 15 April, 2026",
    amountLabel: "Rs. 50,00,000",
    itemOrder: 3,
    source: "seed",
  },
  {
    id: "seed-funding-4",
    title: "Ideas to Impact 3.0",
    description:
      "For impact-focused builders in sustainability, water, energy, agriculture, and waste management.",
    category: "funding",
    status: "published",
    dateLabel: "Deadline: 15 April, 2026",
    amountLabel: "Up to Rs. 1,00,000",
    itemOrder: 4,
    source: "seed",
  },
  {
    id: "seed-funding-5",
    title: "World Bank Youth Summit Hackathon 2026",
    description:
      "Global AI Hackathon for innovators aged 18-35 to build impactful solutions and gain global exposure.",
    category: "funding",
    status: "published",
    dateLabel: "Deadline: 17 April, 2026",
    amountLabel: "NA",
    itemOrder: 5,
    source: "seed",
  },
  {
    id: "seed-funding-6",
    title: "WBG Youth Summit - FutureWorks: Designing Jobs for the Digital Age",
    description:
      "Call for speakers. A global forum for young leaders and experts tackling development challenges.",
    category: "funding",
    status: "published",
    dateLabel: "Deadline: 1 May, 2026",
    amountLabel: "NA",
    itemOrder: 6,
    source: "seed",
  },
  {
    id: "seed-funding-7",
    title: "Stand-Up India Scheme (Govt. of India)",
    description: "Support for SC/ST and women entrepreneurs to start businesses.",
    category: "funding",
    status: "published",
    dateLabel: "Deadline: Rolling basis",
    amountLabel: "Rs. 10 Lakhs to Rs. 1 Crore",
    itemOrder: 7,
    source: "seed",
  },
  {
    id: "seed-funding-8",
    title: "Startup support for PoC and commercialization",
    description:
      "Financial assistance for proof of concept, prototypes, product trials, market entry, and commercialization.",
    category: "funding",
    status: "published",
    dateLabel: "Deadline: Rolling basis",
    amountLabel:
      "Rs. 20 lakhs grant for PoC/prototype and up to Rs. 50 lakhs debt/convertible debentures for commercialization",
    itemOrder: 8,
    source: "seed",
  },
  {
    id: "seed-events-1",
    title: "Cokarma Run Club",
    description:
      "GroundZero with support from Decathlon and Fisique Fitness.",
    category: "events",
    status: "published",
    dateLabel: "Date: 11 April, 2026",
    timeLabel: "Time: 6:30 AM",
    venue: "Cokarma, Kokapet, Hyderabad",
    itemOrder: 1,
    source: "seed",
  },
  {
    id: "seed-events-2",
    title: "GENESIS Edition 1",
    description: "A builder-first meetup focused on genuine founder connections.",
    category: "events",
    status: "published",
    dateLabel: "Date: 12 April, 2026",
    timeLabel: "Time: 10:00 AM - 1:00 PM",
    venue: "Kondapur, Hyderabad",
    itemOrder: 2,
    source: "seed",
  },
  {
    id: "seed-events-3",
    title: "The Founders Circle Meet-up Edition 4",
    description:
      "Featuring Ajay Jain, Founder and Managing Partner of SilverX Fund.",
    category: "events",
    status: "published",
    dateLabel: "Date: 12 April, 2026",
    timeLabel: "Time: 5:00 PM - 8:00 PM",
    venue: "Jubilee Hills, Hyderabad",
    itemOrder: 3,
    source: "seed",
  },
  {
    id: "seed-events-4",
    title: "Open Notes Edition 3",
    description:
      "Breakfast conversation with Sudheer Bandaru (Founder and CEO, Hivel) on founder thinking from 0 to 1.",
    category: "events",
    status: "published",
    dateLabel: "Date: 12 April, 2026",
    timeLabel: "Time: 9:00 AM",
    venue: "Hyderabad",
    itemOrder: 4,
    source: "seed",
  },
  {
    id: "seed-events-5",
    title: "How To Turn 20 Users Into 200",
    description:
      "Virtual session by Bizowl on user growth, channel selection, and early scaling strategy.",
    category: "events",
    status: "published",
    dateLabel: "Date: 16 April, 2026",
    timeLabel: "Time: 4:00 PM - 5:30 PM",
    venue: "Virtual/Online",
    itemOrder: 5,
    source: "seed",
  },
  {
    id: "seed-events-6",
    title: "Hyderabad Social Impact Mixer 11th Edition",
    description:
      "Connect government, CSR leaders, investors, social entrepreneurs, and incubators.",
    category: "events",
    status: "published",
    dateLabel: "Date: 16 April, 2026",
    timeLabel: "Time: 5:30 PM",
    venue: "Aamro Cafe, Gachibowli",
    itemOrder: 6,
    source: "seed",
  },
  {
    id: "seed-events-7",
    title: "Ideas Over Idli #5 - Founder Stories and Startup Conversations",
    description:
      "Sravanth Gajula in conversation with Tarun Mor on practical startup scaling insights.",
    category: "events",
    status: "published",
    dateLabel: "Date: 18 April, 2026",
    timeLabel: "Time: 10:00 AM - 1:00 PM",
    venue: "Cokarma, Kokapet, Hyderabad",
    itemOrder: 7,
    source: "seed",
  },
  {
    id: "seed-events-8",
    title: "Founder Growth Circle",
    description:
      "High-impact networking and peer-learning for builders in Hyderabad.",
    category: "events",
    status: "published",
    dateLabel: "Date: 18 April, 2026",
    timeLabel: "Time: 11:00 AM - 1:00 PM",
    venue: "Cohort Coworking, Raidurgam",
    itemOrder: 8,
    source: "seed",
  },
  {
    id: "seed-events-9",
    title: "Building a Personal Brand as a Founder (Live Session)",
    description:
      "Build a strong personal brand to drive organic growth and reduce CAC.",
    category: "events",
    status: "published",
    dateLabel: "Date: 19 April, 2026",
    timeLabel: "Time: 12:00 PM",
    venue: "Virtual/Online",
    itemOrder: 9,
    source: "seed",
  },
  {
    id: "seed-events-10",
    title: "Into the Investor's Mind by build3",
    description:
      "Virtual session led by angel investor Rajiv Indimath on fundraising fundamentals.",
    category: "events",
    status: "published",
    dateLabel: "Date: 18 April, 2026",
    timeLabel: "Time: 11:00 AM - 12:00 PM",
    venue: "Virtual/Online",
    itemOrder: 10,
    source: "seed",
  },
  {
    id: "seed-events-11",
    title: "Learn the Rules. Raise the Fund.",
    description:
      "Three-day virtual masterclass on pitch decks, valuations, legal term sheets, and investor outreach.",
    category: "events",
    status: "published",
    dateLabel: "Date: 15-19 April, 2026",
    timeLabel: "Time: 6:00 PM - 9:00 PM",
    venue: "Virtual/Online",
    itemOrder: 11,
    source: "seed",
  },
  {
    id: "seed-news-1",
    title: "India's startup ecosystem crosses 2.25 lakh DPIIT-recognised ventures",
    description: "A decade milestone for growth, resilience, and reinvention.",
    category: "news",
    status: "published",
    link:
      "https://www.tice.news/tice-trending/indias-startup-story-hits-225-lakh-mark-a-decade-of-relentless-growth-resilience-and-reinvention-11703859",
    itemOrder: 1,
    source: "seed",
  },
  {
    id: "seed-news-2",
    title: "KTR showcases Telangana's growth story at Columbia Business School",
    description: "Policy and ecosystem momentum update from Telangana.",
    category: "news",
    status: "published",
    link: "https://telanganatoday.com/ktr-showcases-telanganas-growth-story-at-columbia-business-school-conference",
    itemOrder: 2,
    source: "seed",
  },
  {
    id: "seed-hiring-1",
    title: "FundTQ | Investment Banking Analyst",
    description: "Experience: 1-2 years | Remuneration: NA | Location: Gurgaon",
    category: "hiring",
    status: "published",
    itemOrder: 1,
    source: "seed",
  },
  {
    id: "seed-hiring-2",
    title: "VJTI-TBI Foundation | Investment and Portfolio Manager",
    description: "Experience: 1-3 years | Up to Rs. 60,000/month | Location: Mumbai",
    category: "hiring",
    status: "published",
    dateLabel: "Apply by: 30 April, 2026",
    itemOrder: 2,
    source: "seed",
  },
  {
    id: "seed-hiring-3",
    title: "BetaFin Partners | Associate - Founder's Office",
    description: "Experience: 0-2 years | Remuneration: NA | Location: Belur, West Bengal",
    category: "hiring",
    status: "published",
    itemOrder: 3,
    source: "seed",
  },
  {
    id: "seed-hiring-4",
    title: "Pavestone | Investment Team",
    description: "Experience: 1-2 years | Remuneration: NA | Location: Hyderabad or Bengaluru",
    category: "hiring",
    status: "published",
    itemOrder: 4,
    source: "seed",
  },
  {
    id: "seed-new-1",
    title: "Idea Validation Support (3 more founders eligible)",
    description:
      "AI agentic beta-testing support to help find users, run campaigns, identify channels, and connect with creators and community partners.",
    category: "something_new",
    status: "published",
    itemOrder: 1,
    source: "seed",
  },
  {
    id: "seed-new-2",
    title: "Bower Thought Leadership Closed Group",
    description:
      "Founder thought leadership for organic brand growth, reputation, and inbound opportunities. Writing plus consistency.",
    category: "something_new",
    status: "published",
    itemOrder: 2,
    source: "seed",
  },
  {
    id: "seed-new-3",
    title: "1:1 Office Hours Are Now Live",
    description:
      "Get support on discovery, talent, mentorship, wellbeing, and next-step clarity. Reach coordinator or DM on Slack to book.",
    category: "something_new",
    status: "published",
    itemOrder: 3,
    source: "seed",
  },
];
