// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function readEnv(...candidates: Array<string | undefined>) {
  for (const candidate of candidates) {
    if (typeof candidate !== 'string') continue;

    const value = candidate.trim().replace(/^"(.*)"$/, '$1');
    if (!value) continue;
    if (value.toLowerCase() === 'undefined' || value.toLowerCase() === 'null') continue;

    return value;
  }

  return '';
}

function createSupabaseClient() {
  // Prefer VITE_ values injected by Vite from .env, then SSR fallbacks.
  const SUPABASE_URL = readEnv(import.meta.env.VITE_SUPABASE_URL, process.env.SUPABASE_URL);
  const SUPABASE_PUBLISHABLE_KEY = readEnv(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY, process.env.SUPABASE_PUBLISHABLE_KEY);

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error(
      'Missing Supabase environment variables. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in .env (or SUPABASE_URL/SUPABASE_PUBLISHABLE_KEY for SSR fallback).'
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

